#!/usr/bin/env python

'''A standalone node for testing the SailController.cfg dynamic reconfigure config file.
'''

import rospy

from dynamic_reconfigure.server import Server
from rs750_controller.cfg import SailControllerConfig

def callback(config, level):
    rospy.loginfo('sail_angle_attack_deg: {sail_angle_attack_deg}'.format(**config))
    rospy.loginfo('sail_angle_min_deg   : {sail_angle_min_deg}'.format(**config))
    rospy.loginfo('sail_angle_max_deg   : {sail_angle_max_deg}'.format(**config))

    return config

if __name__ == "__main__":
    rospy.init_node("sail_controller_config", anonymous = False)

    srv = Server(SailControllerConfig, callback)
    rospy.spin()
