#!/usr/bin/env python

# Copyright (C) 2020  Rhys Mainwaring
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

'''A standalone node for testing the SailController.cfg dynamic reconfigure config file.
'''

import rospy

from dynamic_reconfigure.server import Server
from rs750_controller.cfg import SailControllerConfig

def callback(config, level):
    rospy.loginfo('sail_angle_attack_deg: {sail_angle_attack_deg}'.format(**config))
    rospy.loginfo('sail_angle_min_deg   : {sail_angle_min_deg}'.format(**config))
    rospy.loginfo('sail_angle_max_deg   : {sail_angle_max_deg}'.format(**config))

    return config

if __name__ == "__main__":
    rospy.init_node("sail_controller_config", anonymous = False)

    srv = Server(SailControllerConfig, callback)
    rospy.spin()
